In [1]:
import os
import keras
import metrics
import numpy as np
import pandas as pd
import keras.backend as K

from time import time

from keras import callbacks
from keras.models import Model
from keras.optimizers import SGD
from keras.layers import Dense, Input
from keras.initializers import VarianceScaling
from keras.engine.topology import Layer, InputSpec

from scipy.misc import imread
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score, normalized_mutual_info_score

/Users/dipanjanpaul/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/dipanjanpaul/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/Users/dipanjanpaul/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/dipanjanpaul/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/dipanjanpaul/anaconda3/lib/python3.6/importlib/_bo

In [2]:
import pickle, gzip, numpy

# Load the dataset
f = gzip.open('mnist_py3k.pkl.gz', 'rb')
train_set, valid_set, test_set = pickle.load(f)
f.close()

In [4]:
train_set[0].shape

(50000, 784)

In [3]:
train_set

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([5, 0, 4, ..., 8, 4, 8]))

In [4]:
len(train_set[0][1])

784

In [6]:
train_set[0][0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [6]:
from keras.layers import Dropout

In [7]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(64, activation='relu', input_dim=784))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
catg_labels = keras.utils.to_categorical(train_set[1], num_classes=10)
model.fit(train_set[0], catg_labels, epochs=10, batch_size=5000)

Epoch 1/10
50000/50000 [==============================] - 1s 17us/step - loss: 2.0673 - acc: 0.2653
Epoch 2/10
50000/50000 [==============================] - 1s 12us/step - loss: 1.5695 - acc: 0.4958
Epoch 3/10
50000/50000 [==============================] - 1s 13us/step - loss: 1.2586 - acc: 0.6020
Epoch 4/10
50000/50000 [==============================] - 1s 12us/step - loss: 1.0727 - acc: 0.6629
Epoch 5/10
50000/50000 [==============================] - 1s 13us/step - loss: 0.9321 - acc: 0.7090
Epoch 6/10
50000/50000 [==============================] - 1s 13us/step - loss: 0.8370 - acc: 0.7418
Epoch 7/10
50000/50000 [==============================] - 1s 13us/step - loss: 0.7593 - acc: 0.7673
Epoch 8/10
50000/50000 [==============================] - 1s 13us/step - loss: 0.7058 - acc: 0.7863
Epoch 9/10
50000/50000 [==============================] - 1s 13us/step - loss: 0.6565 - acc: 0.8044
Epoch 10/10
50000/50000 [==============================] - 1s 13us/step - loss: 0.6128 - acc: 0.8183

In [9]:
vald_y = keras.utils.to_categorical(valid_set[1], num_classes=10)
score = model.evaluate(valid_set[0], vald_y, batch_size=5000)

10000/10000 [==============================] - 0s 11us/step


In [10]:
score

[0.28730496764183044, 0.9196999967098236]

In [11]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

# Generate dummy data
import numpy as np
x_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          epochs=10,
          batch_size=5000)
score = model.evaluate(x_test, y_test, batch_size=5000)

Epoch 1/10
1000/1000 [==============================] - 0s 196us/step - loss: 2.3684 - acc: 0.1000
Epoch 2/10
1000/1000 [==============================] - 0s 10us/step - loss: 2.3688 - acc: 0.1100
Epoch 3/10
1000/1000 [==============================] - 0s 15us/step - loss: 2.3610 - acc: 0.0940
Epoch 4/10
1000/1000 [==============================] - 0s 18us/step - loss: 2.3544 - acc: 0.1000
Epoch 5/10
1000/1000 [==============================] - 0s 17us/step - loss: 2.3577 - acc: 0.0890
Epoch 6/10
1000/1000 [==============================] - 0s 19us/step - loss: 2.3504 - acc: 0.1190
Epoch 7/10
1000/1000 [==============================] - 0s 13us/step - loss: 2.3363 - acc: 0.1300
Epoch 8/10
1000/1000 [==============================] - 0s 10us/step - loss: 2.3587 - acc: 0.1110
Epoch 9/10
1000/1000 [==============================] - 0s 18us/step - loss: 2.3446 - acc: 0.1160
Epoch 10/10
100/100 [==============================] - 0s 751us/step


In [27]:
score

[2.302482843399048, 0.12999999523162842]

In [23]:
np.unique(valid_set[1])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])